#!/bin/bash
npm run build
cp manifest.json /home/shtirliz/.my-links/logs-obsidian/.obsidian/plugins/yamt/
cp main.js /home/shtirliz/.my-links/logs-obsidian/.obsidian/plugins/yamt/
cp styles.css /home/shtirliz/.my-links/logs-obsidian/.obsidian/plugins/yamt/